import { makeStyles } from '@material-ui/core'

const createMyStyle = makeStyles(theme => {
  return {
    myClass: {
      backgroundColor: ({ bg }) => bg,
      position: ({ pos }) => pos,
      right: ({ right }) => right,
      left: ({ left }) => left,
      top: ({ top }) => top,
      zIndex: ({ zIndex }) => zIndex,
      bottom: ({ bottom }) => bottom,
      fontSize: ({ fs }) => fs,
      color: ({ col }) => col,
      minWidth: ({ mw }) => mw,
      width: ({ w }) => w,
      height: ({ h }) => h,
      padding: ({ pa }) => pa,
      paddingTop: ({ pt }) => pt,
      paddingRight: ({ pr }) => pr,
      paddingBottom: ({ pb }) => pb,
      paddingLeft: ({ pl }) => pl,
      marginTop: ({ mt }) => mt,
      marginRight: ({ mr }) => mr,
      marginBottom: ({ mb }) => mb,
      marginLeft: ({ ml }) => ml,
      transform: ({ Y, X, sc }) => `translate(${Y}px, ${X}px) scale(${sc})`,
      '&:hover': {
        background: ({ hvBg }) => hvBg,
        transform: ({ hvSc }) => `scale(${hvSc})`,
      },
      '&:active': {
        transform: ({ avSc, avtlX, avtlY }) =>
          `translate(${avtlX}px, ${avtlY}px) scale(${avSc})`,
      },
    },
  }
})

const makeMyStyle = ({
  mw,
  w,
  h,
  pr,
  pl,
  pt,
  pb,
  pa,
  mt,
  mr,
  mb,
  ml,
  bg,
  col,
  hvBg,
  Y = 0,
  X = 0,
  sc = 1,
  hvSc,
  avSc,
  avtlX = 0,
  avtlY = 0,
  fs,
  pos,
  right,
  left,
  top,
  bottom,
  zIndex,
}) =>
  createMyStyle({
    mw,
    w,
    h,
    pr,
    pl,
    pt,
    pb,
    pa,
    mt,
    mr,
    mb,
    ml,
    bg,
    col,
    hvBg,
    Y,
    X,
    sc,
    hvSc,
    avSc,
    avtlY,
    avtlX,
    fs,
    pos,
    right,
    left,
    top,
    bottom,
    zIndex,
  }).myClass

export default makeMyStyle
