const THEMES_KEYS = Object.freeze({
  DARK: 'DARK',
  LIGHT_TYPE_ONE: 'LIGHT_TYPE_ONE',
  LIGHT_TYPE_TWO: 'LIGHT_TYPE_TWO',
  LIGHT_TYPE_THREE: 'LIGHT_TYPE_THREE',
  LIGHT_TYPE_FOUR: 'LIGHT_TYPE_FOUR',
  LIGHT_TYPE_FIVE: 'LIGHT_TYPE_FIVE',
  LIGHT_TYPE_SIX: 'LIGHT_TYPE_SIX',
  LIGHT_TYPE_SEVEN: 'LIGHT_TYPE_SEVEN',
  LIGHT_TYPE_EIGHT: 'LIGHT_TYPE_EIGHT',
})

export default THEMES_KEYS
